version: '2'
services:
    goldentown2-app:
        image: goldentown2
        external_links:
            - goldentown2-mysql:mysql
            - goldentown2-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/goldentown2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    goldentown2-mysql:
        extends:
            file: mysql.yml
            service: goldentown2-mysql
    goldentown2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: goldentown2-elasticsearch
